### ISSUE TITLE
Redesign of the tool

### ISSUE THREAD

**Issue by sabatesduran** [ondras/wwwsqldesigner#252]
This guy did a very good job:
https://github.com/Lt-Mayonesa/sqldesigner
Demo: https://lt-mayonesa.github.io/sqldesigner/

He deleted all the server side but it can be added againg and use his design.

What do you think @lt-mayonesa

**Comment by Lt-Mayonesa** [comment]
Hey @sabatesduran, thanks!

You wanna merge my fork here? i'll be super honored if you did :smile:

 pd: I didn't touch the server side, so it should just work

**Comment by sabatesduran** [comment]
@Lt-Mayonesa I think your interface is really cool and modern i will try to do it

**Comment by Lt-Mayonesa** [comment]
@sabatesduran :blush: , please do! I don't really have much time in my hands right now.

**Comment by Lt-Mayonesa** [comment]
@sabatesduran Hey! so i went ahead and created the pull request!! Here we go :smile:

**Comment by ianshepherd** [comment]
Interestingly, I can add a table at https://lt-mayonesa.github.io/sqldesigner/ using Chrome (but only if I drag out an area after clicking the 'add table' button - a simple click doesn't work), but I can't on the main branch...

**Comment by Lt-Mayonesa** [comment]
Could it be related to this? #246 

Also, by the main branch, are you referring to this [https://github.com/Lt-Mayonesa/wwwsqldesigner](https://github.com/Lt-Mayonesa/wwwsqldesigner) or [Ondras's Desginer](https://github.com/ondras/wwwsqldesigner)?

**Comment by ianshepherd** [comment]
Sorry for not being clear - I meant Ondras' wwwsqldesigner did not let me add a table, either his hosted demo, or his code on my website. However, I have since discovered it _does_ work if I double-click in the workspace.

The other weird thing is it's similar to #246, but the mouse/trackpad behaviour is different. The only way I can add a table with the trackpad is to double-click; if I use a mouse, I can't add a table by single-clicking or double-clicking, yet I _can_ add one by clicking my scroll wheel, which is programmed to issue a double-click!

I'll add this observation to #246 too...
